import { Poppins, Palanquin} from "next/font/google";
import "./globals.css";
import PropertyProvider from "@/contexts/PropertyContext";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Next Estate",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const palanquin = Palanquin({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-palanquin",
});


export default function RootLayout({ children }) {
  return (
    <PropertyProvider>
    <html lang="en" className='scrollbar-thin scrollbar-track-zinc-50/5 scrollbar-thumb-zinc-50/10'>
      <body
        className={`  antialiased ${poppins.variable} ${palanquin.variable}`}
      >
        <div className=" min-h-[100dvh] grid-row-[auto_1fr_auto]  ">
          <Header />
          <div>
          {children}
          </div>
          <Footer />
        </div>
        
      </body>  
    </html>
    </PropertyProvider>
  );
}
